name: playgrounds
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - ipython
  - pandas
  - traitlets
  - matplotlib
  - numpy
  - python=3.7
  - ipywidgets
  - scikit-learn
  - notebook
  - jupiter
  - jupyter_contrib_nbextensions
  - watermark
  - autopep8
  - xlrd
  - openpyxl

