name: playgrounds
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - ipython
  - pandas
  - traitlets
  - matplotlib
  - numpy
  - scipy
  - python=3.7
  - pyntacle=1.3.2
  - ipywidgets
  - scikit-learn
  - notebook
  - jupyter_contrib_nbextensions
  - watermark
  - autopep8
  - xlrd
  - openpyxl
  - dash-bootstrap-components
  - dash
  - scikit-learn
  - dash_cytoscape
