name: playgrounds
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - traitlets
  - ipython
  - ipywidgets  
  - openpyxl
  - python=3.7
  - notebook
  - jupiter
  - jupyter_contrib_nbextensions
  - watermark
  - autopep8

